// Random mythical creature data that is added to Firestore
// After you've signed into Mythical Menagerie, click the dropdown
// menu in the top right corner and select "Add random data"

export const randomData = {
  creatureNames: [
    "Ancient Dragon",
    "Crystal Unicorn",
    "Phoenix Rising",
    "Golden Griffin",
    "Shadow Basilisk",
    "Deep Kraken",
    "Cerberus Guardian",
    "Winged Pegasus",
    "Fire Salamander",
    "Ice Phoenix",
    "Thunderbird",
    "Sea Serpent",
    "Forest Dryad",
    "Mountain Troll",
    "Desert Djinn",
    "Sky Dragon",
    "Earth Elemental",
    "Water Nymph",
    "Wind Spirit",
    "Lightning Sprite",
    "Crystal Golem",
    "Shadow Wolf",
    "Golden Eagle",
    "Silver Wolf",
    "Bronze Bull",
    "Emerald Serpent",
    "Ruby Tiger",
    "Sapphire Bear",
    "Diamond Lion",
    "Pearl Swan",
    "Coral Mermaid",
    "Amber Phoenix",
    "Jade Dragon",
    "Onyx Panther",
    "Topaz Fox",
    "Garnet Hawk",
    "Opal Owl",
    "Turquoise Dolphin",
    "Lapis Whale",
    "Quartz Deer",
    "Agate Horse",
    "Moonstone Cat",
  ],
  creatureHabitats: [
    "Enchanted Forest",
    "Dragon's Lair",
    "Mystic Pool",
    "Ice Palace",
    "Thunder Peak",
    "Golden Meadow",
    "Emerald Grove",
    "Ruby Desert",
    "Sapphire Ocean",
    "Coral Reef",
  ],
  creatureTypes: [
    "Flying",
    "Aquatic",
    "Terrestrial",
    "Magical",
    "Fire-breathing",
    "Electric",   
    "Light-emitting",
    "Elemental",    
  ],
  mythologyOrigins: [
    "Greco-Roman",
    "Norse",
    "Middle Eastern",
    "Chinese",
    "Celtic",
    "Hindu",
    "Southeast Asian",
    "African",
    "Native American",
    "Mesoamerican",
    "Polynesian",
    "Australian Aboriginal",
  ],
  creatureReviews: [
    { text: "Absolutely magnificent creature! The behavior was fascinating to observe.", rating: 5 },
    { text: "Incredible interaction and the creature was so majestic!", rating: 5 },
    { text: "The creature's appearance was breathtaking and magical.", rating: 5 },
    { text: "Amazing habitat design and the creature seemed very content.", rating: 5 },
    { text: "A truly magical experience that I'll never forget!", rating: 5 },
    {
      text: "The creature's intelligence and grace left me in complete awe.",
      rating: 5,
    },
    { text: "Perfectly cared for creature with excellent habitat conditions.", rating: 5 },
    { text: "Incredible display of natural behaviors and stunning beauty.", rating: 5 },
    { text: "Good creature interaction and well-maintained habitat.", rating: 4 },
    { text: "Enjoyed the visit, would definitely come back again.", rating: 4 },
    { text: "Interesting creature with reasonable viewing opportunities.", rating: 4 },
    { text: "The creature was okay, but the habitat could be improved.", rating: 3 },
    { text: "Decent experience, but nothing extraordinary.", rating: 3 },
    { text: "The creature was average, could be more engaging.", rating: 3 },
    {
      text: "The creature seemed stressed and the habitat was disappointing.",
      rating: 2,
    },
    { text: "Expected more interaction, but left unsatisfied.", rating: 2 },
    { text: "Underwhelming creature behavior and poor habitat design.", rating: 2 },
    { text: "Disappointing visit overall.", rating: 2 },
    {
      text: "The creature was clearly distressed, will never visit again.",
      rating: 1,
    },
    {
      text: "Worst zoo experience I've had so far.",
      rating: 1,
    },
    { text: "Avoid this exhibit, the creature seemed unhealthy.", rating: 1 },
    { text: "Poor creature welfare and inadequate habitat.", rating: 1 },
    { text: "Simply outstanding! A truly magical creature encounter.", rating: 5 },
    { text: "Couldn't get enough of watching this amazing creature.", rating: 5 },
    { text: "Top-notch creature care, worth every moment.", rating: 5 },
    { text: "Highly recommended for creature enthusiasts.", rating: 5 },
    { text: "Exquisite creature that captivated my attention completely.", rating: 5 },
    { text: "A gem of an exhibit, impeccable in every aspect.", rating: 5 },
    { text: "Excellent creature variety and natural behaviors on display.", rating: 5 },
    { text: "A fantastic creature viewing experience overall.", rating: 5 },
    {
      text: "The habitat was lovely, perfect for creature observation.",
      rating: 4,
    },
    { text: "Good creature interaction, but the habitat could be improved.", rating: 4 },
    {
      text: "Pleasantly surprised by the creature's intelligence and behavior.",
      rating: 4,
    },
    { text: "Well-cared for creature and friendly zoo staff.", rating: 4 },
    { text: "Satisfying creature encounter, suitable for a quick visit.", rating: 4 },
    { text: "The creature was okay, nothing special.", rating: 3 },
    {
      text: "Habitat could be better, but the creature was fine.",
      rating: 3,
    },
    {
      text: "An average experience, didn't leave a lasting impression.",
      rating: 3,
    },
    { text: "Expected more creature interaction for the price.", rating: 2 },
    { text: "Mediocre creature behavior and lackluster habitat design.", rating: 2 },
    {
      text: "Regret spending money on such a disappointing creature exhibit.",
      rating: 2,
    },
    { text: "Not up to par with my expectations for creature welfare.", rating: 2 },
  ],
};
